urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from accounts.views import UserProfileView, OwnUserProfileView,\
    PhoneVerificationView, RequestNewVerificationCodeView, ProfileUpdateView
from listings.views import AllReviewsView, OwnerListingView, ListingCreateView,\
    ListingDetailView, ListingUpdateView, TicketSearchView, ListingDeleteView, \
    ReviewUserView, IndexView, transaction_update
from events.views import event_json, venue_json
from allauth.account.views import login
admin.autodiscover()

urlpatterns = [
    url(r'^$', IndexView.as_view(), name="home"),
    url(r'^accounts/login/$', login, name="login"), # login url for things that need it
    url(r'^accounts/', include('allauth.urls')),
    url(r'^verify_phone/$', PhoneVerificationView.as_view(), name="phone_verification"),
    url(r'^verify_phone/new/$', RequestNewVerificationCodeView.as_view(), name="new_verification_code"),
    url(r'^profile/$', OwnUserProfileView.as_view(), name="profile"),
    url(r'^profile/edit/$', ProfileUpdateView.as_view(), name="edit_profile"),
    url(r'^users/(?P<pk>[0-9]+)/$', UserProfileView.as_view(), name="profile_user"),
    url(r'^users/(?P<pk>[0-9]+)/reviews/$', AllReviewsView.as_view(), name="all_reviews_view"),
    url(r'^users/(?P<pk>[0-9]+)/listings/$', OwnerListingView.as_view(), name="owner_list_view"),
    url(r'^events/', include('events.event_urls')),
    url(r'^venues/', include('events.venue_urls')),

    url(r'^listings/$', TicketSearchView.as_view(), name="ticket_list"),
    url(r'^listings/create/$', ListingCreateView.as_view(), name="post"),
    url(r'^listings/(?P<pk>[0-9]+)/$',ListingDetailView.as_view(), name="ticket_view"),
    url(r'^listings/(?P<pk>[0-9]+)/edit/$',ListingUpdateView.as_view(), name="ticket_edit"),
    url(r'^listings/(?P<pk>[0-9]+)/delete/$',ListingDeleteView.as_view(), name="ticket_delete"),

    url(r'^reviews/(?P<transaction_id>[0-9]+)/create/$', ReviewUserView.as_view(), name="create_review"),

    url(r'^list/event/', event_json),
    url(r'^list/venue/', venue_json),

    url(r'^transaction/update/', transaction_update, name='transaction_update'),
    url(r'^wishlist/', include('wishlist.urls')),

    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),

    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^faq/$', TemplateView.as_view(template_name='pages/faq.html'), name='faq'),
    url(r'^privacy_policy/$', TemplateView.as_view(template_name='pages/privacy_policy.html'), name='privacy_policy'),
    url(r'^terms_of_user/$', TemplateView.as_view(template_name='pages/terms_of_use.html'), name='terms_of_use'),
    url(r'^contact/$', TemplateView.as_view(template_name='pages/contact.html'), name='contact'),

    url(r'^admin/', include(admin.site.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
     #         + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

handler404 = 'views.handler404'

events/models.py
import os

from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from django.db import models
from versatileimagefield.placeholder import OnDiscPlaceholderImage

from accounts.models import User
from datetime import datetime
from taggit.managers import TaggableManager
from regions.models import Region
from versatileimagefield.fields import VersatileImageField, OnStoragePlaceholderImage


class Venue(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    user = models.ForeignKey(User, related_name='venue', null=True)
    bio = models.CharField(max_length=2048, blank=True)
    type = models.CharField(max_length=100, blank=True)
    link = models.URLField(blank=True)
    image = VersatileImageField(
        'Image',
        upload_to='images/venues/',
        width_field='width',
        height_field='height',
        blank=True,
        placeholder_image=OnDiscPlaceholderImage(
            path=os.path.join(
                settings.BASE_DIR,
                'static',
                'placeholder_images',
                'placeholder.jpg'
            )
        )
    )
    height = models.PositiveIntegerField(
        'Image Height',
        blank=True,
        null=True
    )
    width = models.PositiveIntegerField(
        'Image Width',
        blank=True,
        null=True
    )
    address = models.CharField(max_length=2048, blank=True)
    city = models.CharField(max_length=128, blank=True)
    state = models.CharField(max_length=128, blank=True)
    region = models.ForeignKey(Region)

    alcohol_available = models.BooleanField(default=False)
    food_available = models.BooleanField(default=False)
    numbered_seats = models.BooleanField(default=False)
    coat_check_available = models.BooleanField(default=False)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('profile_venue', args=(self.slug,))

    @property
    def full_address(self):
        return ", ".join((self.address, self.city, self.state))

    def upcoming_events(self):
        return self.events.filter(start_time__gte=datetime.now().date())

    def google_maps_uri(self):
        api_key = "AIzaSyCYDsKfRNswFuTYAamB88mIBXwkI1sqTLI"
        if self.address and self.city and self.state:
            return "https://www.google.com/maps/embed/v1/place?key=%s&q=%s,%s+%s" % (api_key, self.address, self.city, self.state)

        return None


class EventManager(models.Manager):

    def upcoming_events(self):
        return self.filter(start_time__gte=datetime.now().date())


class Event(models.Model):
    name = models.CharField(max_length=255, default='')
    bio = models.TextField(blank=True)
    start_time = models.DateTimeField()
    bands = models.CharField(max_length=255, blank=True)
    venue = models.ForeignKey('Venue', null=True, related_name='events')
    user = models.ForeignKey(User)
    image = VersatileImageField(
        'Image',
        upload_to='images/events/',
        width_field='width',
        height_field='height',
        blank=True,
        placeholder_image=OnDiscPlaceholderImage(
            path=os.path.join(
                settings.BASE_DIR,
                'static',
                'placeholder_images',
                'placeholder.jpg'
            )
        )
    )
    height = models.PositiveIntegerField(
        'Image Height',
        blank=True,
        null=True
    )
    width = models.PositiveIntegerField(
        'Image Width',
        blank=True,
        null=True
    )
    region = models.ForeignKey(Region)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tags = TaggableManager(blank=True)
    objects = EventManager()

    class Meta:
        ordering = ('start_time',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('profile_event', args=(self.pk,))

    def get_bands_display(self):
        if len(self.bands) > 0:
            return self.bands
        return '-'

    def get_cheapest_price(self):
        return self.tickets.all().order_by('-price').first().price

listings/views.py
from datetime import datetime, date, time

from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseForbidden, JsonResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, TemplateView
from haystack.generic_views import SearchView
from accounts.models import User
from accounts.mixins import VerifiedUserMixin
from accounts.notify import EmailManager
from events.models import Event
from regions.models import Region
from regions.mixins import RegionCreateViewMixin, RegionMixin
from .forms import ListingForm, TicketOfferForm, ListingUpdateForm, ReviewForm, InputFilterForm
from .models import Listing, Transaction, Review


# This is the homepage
class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['listing_list'] = Listing.objects.filter(region=self.request.region).order_by('-create_date').select_related('event').select_related('event__venue')[:8]
        today_min = datetime.combine(date.today(), time.min)
        context['events_list'] = Event.objects.filter(region=self.request.region, start_time__gte=today_min).order_by('start_time').select_related('venue')[:2]
        context['regions'] = Region.objects.all()
        return context


class ListingCreateView(VerifiedUserMixin, RegionCreateViewMixin, CreateView):
    template_name = 'create_form.html'
    model = Listing
    form_class = ListingForm

    def form_valid(self, form):
        form.instance.seller = self.request.user
        return_value = super(ListingCreateView, self).form_valid(form)
        form.instance.save()
        return return_value

    def get_context_data(self, **kwargs):
        context = super(ListingCreateView, self).get_context_data(**kwargs)
        context['title'] = "Post Listing"
        return context


class ListingDetailView(RegionMixin, DetailView):
    context_object_name = 'ticket'
    model = Listing

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = TicketOfferForm(data=self.request.POST, available_tickets=self.object.available_tickets())
        if form.is_valid() and int(form.cleaned_data['quantity']) <= self.object.available_tickets():
            Transaction.objects.create(
                seller=self.object.seller,
                buyer=self.request.user,
                ticket=self.object,
                quantity=form.cleaned_data['quantity'],
                status=Transaction.POSTED,
                price=self.object.price
            )
            messages.success(self.request, 'Your ticket request has been sent to the seller successfully.')
            return HttpResponseRedirect(self.object.get_absolute_url())
        else:
            messages.error(self.request, 'There was a problem sending your request please try again.')
            return self.render_to_response(self.get_context_data(form=form))

    def get_template_names(self):
        if self.request.user.is_authenticated() and self.object.seller == self.request.user:
            return ['listings/listing_details_owner_view.html']
        else:
            return ['listings/listing_details.html']

    def get_context_data(self, **kwargs):
        context = super(ListingDetailView, self).get_context_data(**kwargs)
        context['transaction_list'] = self.object.transactions.all()
        context['form'] = TicketOfferForm(available_tickets=self.object.available_tickets())
        return context


class ListingUpdateView(UpdateView):
    template_name = 'create_form.html'
    model = Listing
    form_class = ListingUpdateForm

    def get_queryset(self):
        return Listing.objects.filter(seller=self.request.user)

    def form_valid(self, form):
        return_value = super(ListingUpdateView, self).form_valid(form)
        form.instance.save()
        return return_value


class ListingDeleteView(DeleteView):
    model = Listing

    def get_queryset(self):
        return Listing.objects.filter(seller=self.request.user)

    def get_success_url(self):
        return reverse_lazy('profile')


class OwnerListingView(ListView):
    template_name = 'listings/listing_list_user.html'
    context_object_name = 'ticket_list'
    model = Listing

    def get_queryset(self):
        pk = self.kwargs.get('pk', None)
        return Listing.objects.filter(seller_id=pk)

    def get_context_data(self, **kwargs):
        context = super(OwnerListingView, self).get_context_data(**kwargs)
        context['account'] = User.objects.get(pk=self.kwargs.get('pk'))
        return context


class AllReviewsView(ListView):
    template_name = 'reviews/all_reviews.html'
    context_object_name = 'review_list'

    def get_queryset(self):
        pk = self.kwargs.get('pk', None)
        return Review.objects.filter(target_id=pk)

    def get_context_data(self, **kwargs):
        context = super(AllReviewsView, self).get_context_data(**kwargs)
        context['account'] = get_object_or_404(User, pk=self.kwargs['pk'])
        return context


class ReviewUserView(CreateView):
    template_name = 'reviews/leave_review.html'
    form_class = ReviewForm
    target = None

    def dispatch(self, request, *args, **kwargs):
        self.get_target()
        if not self.transaction.user_can_review(request.user):
            return HttpResponseRedirect(reverse_lazy('profile'))
        return super(ReviewUserView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ReviewUserView, self).get_context_data(**kwargs)
        context['target'] = self.target
        context['transaction'] = self.transaction
        return context

    def form_valid(self, form):
        review = form.save(commit=False)
        review.creator = self.request.user
        review.target = self.target
        review.transaction = self.transaction
        return super(ReviewUserView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('profile')

    def get_target(self):
        self.transaction = Transaction.objects.get(pk=self.kwargs['transaction_id'])
        if self.transaction.seller == self.request.user:
            self.target = self.transaction.buyer
        else:
            self.target = self.transaction.seller


def transaction_update(request):
    response = {}
    if request.method == 'POST':
        transaction = get_object_or_404(Transaction, pk=request.POST['transaction_id'])
        # TODO: Add proper permissions check
        new_status = request.POST.get('update', None)
        is_updated = transaction.update_status(new_status=new_status)

        if is_updated:
            if new_status == Transaction.COMMITTED:
                notif_mgr = EmailManager()
                notif_mgr.notify_transactees(notif_mgr.COMMIT_NOTIFICATION, transaction.pk)

            elif new_status == Transaction.COMPLETED:
                notif_mgr = EmailManager()
                notif_mgr.notify_transactees(notif_mgr.COMPLETE_NOTIFICATION, transaction.pk)

        response['message'] = is_updated
        return JsonResponse(response, safe=False)
    return HttpResponseForbidden


class TicketSearchView(RegionMixin, SearchView):
    form_class = InputFilterForm
    paginate_by = 10
    context_object_name = 'listings'

    def get_context_data(self, **kwargs):
        context = super(TicketSearchView, self).get_context_data(**kwargs)
        return context

templates/listings/listing_confirm_delete.html
{% extends "base.html" %}
{% block title %}Delete Listing{% endblock %}
{% block content %}
<div class="row">
    <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete your listing {{ object.title }}?</p>
    <input type="submit" value="Confirm" />
</form>

</div>

{% endblock %}

templates/listings/listing_details.html
{% extends "base.html" %}
{% load humanize %}
{% load staticfiles i18n %}
{% load crispy_forms_tags %}

{% block title %}{{ ticket.title }}{% endblock %}
{% block content %}

<section class="mainCotainer" id="listingDetails">
    <article>
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12 col-md-7">
                    <div class="cardTitle">
                        <div class="event">
                            <div class="name">{{ ticket.title }}</div>
                            <div class="date">{{ ticket.event_date }}</div>
                        </div>
                        <div class="info">
                            <div class="price">${{ ticket.price|floatformat:"0" }}</div>
                            <div class="available">{{ ticket.ticket_total }} ticket(s) available</div>
                        </div>
                    </div>
                    <!--<div class="tags">-->
                        <!--<div class="tag">rock</div>-->
                        <!--<div class="tag">k-pop</div>-->
                        <!--<div class="tag">alternative</div>-->
                    <!--</div>-->
                    <div class="seller"><img class="profilePic" src="{{ ticket.seller.image.thumbnail.80x80 }}">
                        <div class="qual">
                            <div class="name">{{ ticket.seller }}</div>
                            <div class="stars">
                                {% if ticket.seller.average_review_score >= 5 %}
                                    <div class="star"></div>
                                    <div class="star"></div>
                                    <div class="star"></div>
                                    <div class="star"></div>
                                    <div class="star"></div>
                                {% elif ticket.seller.average_review_score >= 4 %}
                                    <div class="star"></div>
                                    <div class="star"></div>
                                    <div class="star"></div>
                                    <div class="star"></div>
                                {% elif ticket.seller.average_review_score >= 3 %}
                                    <div class="star"></div>
                                    <div class="star"></div>
                                    <div class="star"></div>
                                {% elif ticket.seller.average_review_score >= 2 %}
                                    <div class="star"></div>
                                    <div class="star"></div>
                                {% elif ticket.seller.average_review_score >= 1 %}
                                    <div class="star"></div>
                                {% else %}
                                    <p>No Reviews</p>
                                {% endif %}
                            </div>
                            <div class="num">({{ ticket.seller.reviews.count }})</div>
                        </div>
                        <div class="attributes">
                            {% if ticket.seller.phone_verified %}
                                <div class="attribute"><img src="/static/images/identity-verified.svg">
                                    <div class="verifyed">Identity Verified</div>
                                </div>
                                <!--<div class="attribute"><img src="/static/images/facebook-verified.svg">-->
                                    <!--<div class="verifyed">Facebook Verified</div>-->
                                <!--</div>-->
                                <div class="attribute"><img src="/static/images/phone-verified.svg">
                                    <div class="verifyed">Phone Verified</div>
                                </div>
                                {% else %}
                                <p>Not verified</p>
                                {% endif %}
                        </div>
                        <div class="des">{{ ticket.description }}</div>
                        <div class="contactButton">
                            {% with ticket.seller as account %}
                            {% if request.user.is_authenticated %}
                            <a href="{% url 'postman:write' account %}" type="button"
                               class="btn btn-default redButton message-button">Contact the Seller</a>
                            {% else %}
                            <a href="{% url 'account_login' %}" type="button"
                               class="btn btn-default red Button message-button">Login to contact the Seller</a>
                            {% endif %}
                            {% endwith %}
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-1"></div>
                <div class="col-xs-12 col-md-4 mmm">
                    <div class="legendFeat container-fluid">
                        <div class="legend">BUYING ON TICKETSLOTH IS SAFE, AFFORDABLE, AND RELIABLE</div>
                        <div class="row buyingRow">
                            <div class="col-xs-12">
                                <div class="feat"><img src="/static/images/buyerprotection-icon.svg">
                                    <div class="info">
                                        <div class="title">BUYER PROTECTION</div>
                                        <div class="des">It was a humorously perilous business for both of us.</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <div class="feat"><img src="/static/images/review-icon.svg">
                                    <div class="info">
                                        <div class="title">REVIEW SYSTEM</div>
                                        <div class="des">It was a humorously perilous business for both of us.</div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <div class="feat"><img src="/static/images/nofees-icon.svg">
                                    <div class="info">
                                        <div class="title">NO FEES</div>
                                        <div class="des">It was a humorously perilous business for both of us.</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="more-info container-fluid">
            <div class="row">
                <div class="col-xs-12 col-md-7">
                    <h2>More information about {{ ticket.seller }}, the seller:</h2>
                    <div class="seller-info"><img class="profilePic" src="{{ ticket.seller.image.thumbnail.150x150 }}">
                        <div class="info">
                            <div class="name">{{ ticket.seller }}</div>
                            <div class="des">{{ ticket.seller.bio }}</div>
                        </div>
                    </div>
                    <div class="buttons">
                        <a href="{{ ticket.seller.get_absolute_url }}" class="redButton outline">SEE SELLER'S PROFILE</a>
                    </div>
                    <div class="reviews">
                        <h2>{{ ticket.seller.reviews.count }} REVIEW(S)
                            <div class="stars">
                            {% if ticket.seller.average_review_score >= 5 %}
                            <div class="star"></div>
                            <div class="star"></div>
                            <div class="star"></div>
                            <div class="star"></div>
                            <div class="star"></div>
                            {% elif ticket.seller.average_review_score >= 4 %}
                            <div class="star"></div>
                            <div class="star"></div>
                            <div class="star"></div>
                            <div class="star"></div>
                            {% elif ticket.seller.average_review_score >= 3 %}
                            <div class="star"></div>
                            <div class="star"></div>
                            <div class="star"></div>
                            {% elif ticket.seller.average_review_score >= 2 %}
                            <div class="star"></div>
                            <div class="star"></div>
                            {% elif ticket.seller.average_review_score >= 1 %}
                            <div class="star"></div>
                            {% else %}
                            <p>No Reviews</p>
                            {% endif %}
                            </div>
                        </h2>
                        <div class="hDivider"></div>
                        {% for review in ticket.seller.reviews.all|slice:":3" %}
                        <div class="reviewListing">
                            <div class="author"><img src="{{ review.creator.image.thumbnail.150x150 }}">
                                <div class="name">{{ review.creator.username }}</div>
                            </div>
                            <div class="review">
                                <img class="trian" src="/static/images/blanktrian2.png">
                                <div class="reviewText">{{ review.message }}</div>
                                <div class="date">{{ review.created_at|date:"F jS Y" }}</div>
                            </div>
                        </div>
                        {% endfor %}

                        <div class="buttons">
                            <a href="{% url 'all_reviews_view' ticket.seller.pk %}" class="redButton outline">SEE ALL REVIEWS</a>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-md-1"></div>
                <div class="col-xs-12 col-md-4"></div>
            </div>
        </div>
        <div class="otherLike">
            <h2>YOU MAY ALSO LIKE</h2>
            {% you_may_also_like request.region 3 %}
        </div>
    </article>
</section>

{% endblock %}

templates/listings/listing_list_item.html
<div class="recentListing">
    <a href="{{ listing.get_absolute_url }}">
        <div class="recentInfo"><img class="artist" src="{{ listing.event.image.thumbnail.80x80 }}">
            <div class="realName">
                <div class="name">{{ listing.get_list_title }}</div>
                <div class="date">{{ listing.get_venue_display }} {{ listing.event_date|date:"M d" }}</div>
            </div>
            <div class="infoCont">
                <div class="comp price">${{ listing.price|floatformat:"0" }}</div>
                <div class="comp tickets">
                    <div class="x">x{{ listing.ticket_total }}</div>
                    <div class="des">ticket(s)</div>
                </div>
            </div>
        </div>
    </a>
    <div class="recentButtons">
        <a href="{{ listing.get_absolute_url }}">
        </a>
        <div class="infoCont">
            <a class="redButton" href="{{ listing.get_absolute_url }}">Buy Tickets</a></div>
    </div>
</div>

templates/listings/listing_list_user.html
{% extends "base.html" %}
{% load staticfiles i18n %}
 {% load humanize %}


{% block content %}
<div class="row">
    <div class="panel panel-default" id="tickettable">

        <!--<div class="panel-heading">Listing Listings:</div> -->
        <div class="panel-body"><b>Showing listings for user {{ user }}</b> <a href = "{% url 'post' %}">post a new ticket</a></div>

        <div class="table-responsive">
            <table id="tickets-list" class = "table table-striped table-bordered">
            <thead>
            <tr>
                <th>Listing Title</th>
                <th>User Name</th>
                <th>Price</th>
                <th>Venue</th>
                <th>Artist(s)</th>
                <th>Posted</th>
            </tr>
            </thead>
            <tbody>
            {% for ticket in ticket_list %}
            <tr>
                <td><a href="{{ ticket.get_absolute_url }}"> {{ticket.title}}</a></td>
                <td><a href="{{ ticket.seller.get_absolute_url }}">{{ticket.seller.username}}</a></td>
                <td>{{ticket.price}}</td>
                <td>{{ticket.get_venue_display}}</td>
                <td>{{ticket.get_band_display}}</td>
                <td>{{ticket.create_date|naturaltime}}</td>
            </tr>
            {% endfor %}

            </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}


{% block javascript %}
<script type="text/javascript">
$(document).ready(function() {
    $('#tickets-list').dataTable();
});
</script>
{% endblock %}