urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from accounts.views import UserProfileView, OwnUserProfileView,\
    PhoneVerificationView, RequestNewVerificationCodeView, ProfileUpdateView
from listings.views import AllReviewsView, OwnerListingView, ListingCreateView,\
    ListingDetailView, ListingUpdateView, TicketSearchView, ListingDeleteView, \
    ReviewUserView, IndexView, transaction_update
from events.views import event_json, venue_json
from allauth.account.views import login
admin.autodiscover()

urlpatterns = [
    url(r'^$', IndexView.as_view(), name="home"),
    url(r'^accounts/login/$', login, name="login"), # login url for things that need it
    url(r'^accounts/', include('allauth.urls')),
    url(r'^verify_phone/$', PhoneVerificationView.as_view(), name="phone_verification"),
    url(r'^verify_phone/new/$', RequestNewVerificationCodeView.as_view(), name="new_verification_code"),
    url(r'^profile/$', OwnUserProfileView.as_view(), name="profile"),
    url(r'^profile/edit/$', ProfileUpdateView.as_view(), name="edit_profile"),
    url(r'^users/(?P<pk>[0-9]+)/$', UserProfileView.as_view(), name="profile_user"),
    url(r'^users/(?P<pk>[0-9]+)/reviews/$', AllReviewsView.as_view(), name="all_reviews_view"),
    url(r'^users/(?P<pk>[0-9]+)/listings/$', OwnerListingView.as_view(), name="owner_list_view"),
    url(r'^events/', include('events.event_urls')),
    url(r'^venues/', include('events.venue_urls')),

    url(r'^listings/$', TicketSearchView.as_view(), name="ticket_list"),
    url(r'^listings/create/$', ListingCreateView.as_view(), name="post"),
    url(r'^listings/(?P<pk>[0-9]+)/$',ListingDetailView.as_view(), name="ticket_view"),
    url(r'^listings/(?P<pk>[0-9]+)/edit/$',ListingUpdateView.as_view(), name="ticket_edit"),
    url(r'^listings/(?P<pk>[0-9]+)/delete/$',ListingDeleteView.as_view(), name="ticket_delete"),

    url(r'^reviews/(?P<transaction_id>[0-9]+)/create/$', ReviewUserView.as_view(), name="create_review"),

    url(r'^list/event/', event_json),
    url(r'^list/venue/', venue_json),

    url(r'^transaction/update/', transaction_update, name='transaction_update'),
    url(r'^wishlist/', include('wishlist.urls')),

    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),

    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^faq/$', TemplateView.as_view(template_name='pages/faq.html'), name='faq'),
    url(r'^privacy_policy/$', TemplateView.as_view(template_name='pages/privacy_policy.html'), name='privacy_policy'),
    url(r'^terms_of_user/$', TemplateView.as_view(template_name='pages/terms_of_use.html'), name='terms_of_use'),
    url(r'^contact/$', TemplateView.as_view(template_name='pages/contact.html'), name='contact'),

    url(r'^admin/', include(admin.site.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
     #         + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

handler404 = 'views.handler404'

events/models.py
import os

from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from django.db import models
from versatileimagefield.placeholder import OnDiscPlaceholderImage

from accounts.models import User
from datetime import datetime
from taggit.managers import TaggableManager
from regions.models import Region
from versatileimagefield.fields import VersatileImageField, OnStoragePlaceholderImage


class Venue(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    user = models.ForeignKey(User, related_name='venue', null=True)
    bio = models.CharField(max_length=2048, blank=True)
    type = models.CharField(max_length=100, blank=True)
    link = models.URLField(blank=True)
    image = VersatileImageField(
        'Image',
        upload_to='images/venues/',
        width_field='width',
        height_field='height',
        blank=True,
        placeholder_image=OnDiscPlaceholderImage(
            path=os.path.join(
                settings.BASE_DIR,
                'static',
                'placeholder_images',
                'placeholder.jpg'
            )
        )
    )
    height = models.PositiveIntegerField(
        'Image Height',
        blank=True,
        null=True
    )
    width = models.PositiveIntegerField(
        'Image Width',
        blank=True,
        null=True
    )
    address = models.CharField(max_length=2048, blank=True)
    city = models.CharField(max_length=128, blank=True)
    state = models.CharField(max_length=128, blank=True)
    region = models.ForeignKey(Region)

    alcohol_available = models.BooleanField(default=False)
    food_available = models.BooleanField(default=False)
    numbered_seats = models.BooleanField(default=False)
    coat_check_available = models.BooleanField(default=False)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('profile_venue', args=(self.slug,))

    @property
    def full_address(self):
        return ", ".join((self.address, self.city, self.state))

    def upcoming_events(self):
        return self.events.filter(start_time__gte=datetime.now().date())

    def google_maps_uri(self):
        api_key = "AIzaSyCYDsKfRNswFuTYAamB88mIBXwkI1sqTLI"
        if self.address and self.city and self.state:
            return "https://www.google.com/maps/embed/v1/place?key=%s&q=%s,%s+%s" % (api_key, self.address, self.city, self.state)

        return None


class EventManager(models.Manager):

    def upcoming_events(self):
        return self.filter(start_time__gte=datetime.now().date())


class Event(models.Model):
    name = models.CharField(max_length=255, default='')
    bio = models.TextField(blank=True)
    start_time = models.DateTimeField()
    bands = models.CharField(max_length=255, blank=True)
    venue = models.ForeignKey('Venue', null=True, related_name='events')
    user = models.ForeignKey(User)
    image = VersatileImageField(
        'Image',
        upload_to='images/events/',
        width_field='width',
        height_field='height',
        blank=True,
        placeholder_image=OnDiscPlaceholderImage(
            path=os.path.join(
                settings.BASE_DIR,
                'static',
                'placeholder_images',
                'placeholder.jpg'
            )
        )
    )
    height = models.PositiveIntegerField(
        'Image Height',
        blank=True,
        null=True
    )
    width = models.PositiveIntegerField(
        'Image Width',
        blank=True,
        null=True
    )
    region = models.ForeignKey(Region)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tags = TaggableManager(blank=True)
    objects = EventManager()

    class Meta:
        ordering = ('start_time',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('profile_event', args=(self.pk,))

    def get_bands_display(self):
        if len(self.bands) > 0:
            return self.bands
        return '-'

    def get_cheapest_price(self):
        return self.tickets.all().order_by('-price').first().price

events/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Field, HTML
from django.utils.text import slugify
import itertools
from .models import Event, Venue
from django.core.urlresolvers import reverse_lazy


STATES = (('--', '--'), ('AK', 'Alaska'), ('AL', 'Alabama'), ('AZ', 'Arizona'),
    ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'),
    ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'),
    ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'),
    ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'),
    ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'),
    ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'),
    ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'),
    ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'),
    ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'),
    ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'))

BUY_OR_SELL = (('False', 'I want to sell tickets'), ('True', 'I want to buy tickets'))


class EventForm(forms.ModelForm):
    name = forms.CharField(label="Name", max_length=255, error_messages={'required': "Please enter a value"})
    bio = forms.CharField(label="Description", widget=forms.Textarea, max_length=2000, required=False)
    start_time = forms.CharField(label="Event Date & Time", max_length=128)
    venue_select = forms.CharField(label="Select Venue", max_length=100)

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['bands'].required=False
        self.fields['venue'].required=False

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                None,
                Field('name', wrapper_class="col-md-12"),
                Field('bio', wrapper_class="col-md-12"),
                Field('image', wrapper_class="col-md-6"),
                Field('start_time', wrapper_class="col-md-6", css_class='start_time'),
                Field('venue_select', wrapper_class="col-md-6 venue-select", css_class='venue_select'),
                Field('venue', type="hidden", css_class='venue_field'),
                Field('bands', wrapper_class="col-md-6", css_class='band_field'),
                Field('tags', placeholder='Tags', wrapper_class="col-md-12"),
                Submit('submit', 'Submit', css_class="create-btn", wrapper_class="col-md-12"),
            )
        )

        self.helper.label_class = "col-lg-12"
        self.helper.field_class = "col-lg-12"

    def clean_start_time(self):
        if self.cleaned_data['start_time'] == '':
            return None
        return self.cleaned_data['start_time'].replace(' ','T')

    class Meta:
        model = Event
        fields = ('name', 'bio', 'start_time', 'bands', 'venue', 'image', 'tags')


class CreateVenueForm(forms.ModelForm):
    name = forms.CharField(label="Name", max_length=255, error_messages={'required': "Please enter a value"})
    bio = forms.CharField(label="Description", widget=forms.Textarea, max_length=2000, required=False)
    address = forms.CharField(label="Address", max_length=255, required=False)
    city = forms.CharField(label="City", max_length=100, required=False)
    state = forms.ChoiceField(label="State", choices=STATES, required=False)

    def __init__(self, *args, **kwargs):
        super(CreateVenueForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                None,
                HTML('<div class="col-md-12"><h3>Add venue details</h3></div>'),
                Field('name', placeholder='Name'),
                Field('bio', placeholder='Description'),
                Field('image'),
                Field('address', placeholder='Street Address'),
                Field('city', placeholder='City'),
                Field('state', placeholder='State'),
                Submit('submit', 'Submit', css_class="create-btn"),
            )
        )
        self.helper.label_class = "col-lg-12"
        self.helper.field_class = "col-lg-12"

    class Meta:
        model = Venue
        fields = ('name', 'bio', 'address', 'city', 'state', 'image')

    def save(self, commit=True):
        instance = super(CreateVenueForm, self).save(commit=False)

        instance.slug = orig = slugify(instance.name)

        for x in itertools.count(1):
            if not Venue.objects.filter(slug=instance.slug).exists():
                break
            instance.slug = '%s-%d' % (orig, x)

        return super(CreateVenueForm, self).save(commit=commit)

wishlist/views.py
import json
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView

from events.models import Event
from .models import WishListEntry


class WishlistView(ListView):
    template_name = 'wishlist/wishlist.html'
    context_object_name = 'wishlist_items'

    def get_queryset(self):
        return WishListEntry.objects.filter(user=self.request.user)

    def post(self, request, *args, **kwargs):
        user = request.user
        if user.is_anonymous():
            return JsonResponse({'message': 'You must be logged in to add to a wishlist.'}, status=401)
        json_data = json.loads(request.body)
        event_id = json_data.get('event_id', None)
        if not event_id:
            return JsonResponse({'message': 'No event in request.'}, status=400)
        try:
            event = Event.objects.get(pk=event_id)
            entry, created = WishListEntry.objects.get_or_create(event=event, user=user)
            if created:
                return JsonResponse({'message': '%s added to wishlist.' % event.name}, status=200)
            else:
                return JsonResponse({'message': '%s already in wishlist.' % event.name}, status=200)
        except Event.DoesNotExist:
            return JsonResponse({'message': 'Event does not exist.'}, status=404)


class WishlistItemDeleteView(DeleteView):
    success_url = reverse_lazy('wishlist')

    def get_queryset(self):
        return WishListEntry.objects.filter(user=self.request.user)

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

templates/base.html
{% load staticfiles i18n %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}{% block head_title %}{% endblock %} - Ticket Sloth</title>

    {% block styles %}{% endblock %}

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-slider.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/nouislider.min.css' %}">

    <meta name="robots" content="nofollow"/>
    {% block extrahead %}{% endblock %}
</head>
<body>
<div class="container background-top">
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar"><span class="sr-only">Toggle navigation</span><span
                        class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                <a class="navbar-brand logo" href="{% url 'home' %}">TicketSloth</a></div>
            <div class="navbar-collapse collapse" id="navbar">
                <ul class="nav navbar-nav main">
                    <li><a href="{% url 'post' %}">Sell Tickets</a></li>
                    <li><a href="{% url 'profile' %}">My Tickets</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right main">
                    <li>
                        <a href="{% url 'postman:inbox' %}">Messages
                            {% if unread_count %}
                                <div style="width: 16px; height: 16px; background-color: #EE190B; border-radius: 50%; position: absolute; color: white; right: 0; top: 10px; font-size: 12px; text-align: center; line-height: 16px;">
                                    {{ unread_count }}
                                </div>
                            {% endif %}
                        </a>
                    </li>
                    <li><a href="{% url 'ticket_list' %}">Listings</a></li>
                    <li><a href="{% url 'event_list' %}">Events</a></li>
                    <li><a href="{% url 'venue_list' %}">Venues</a></li>
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'account_logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
                        <li><a href="{% url 'account_login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
            {% block lower_header %}
                {% include 'partial/partial_searchbar.html' %}
            {% endblock %}
        </div>
    </nav>
</div>

{% if messages %}
    <ul class="list-unstyled messages">
        {% for message in messages %}
            <li class="alert alert-{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<div class="container">
    {% block postman_menu %} {% endblock %}
    {% block content %}
    {% endblock %}
</div>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
<script src="{% static 'js/ajax_setup.js' %}"></script>
<script src="{% static 'js/wishlist.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/nouislider.min.js' %}"></script>
{% block javascript %}
{% endblock %}

</body>

</html>

templates/create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles i18n %}

{% block title %}{{ title }}{% endblock %}

{% block lower_header %}
    <div class="mainTitle">{{ title }}</div>
{% endblock %}

{% block content %}
    <div class="row col-md-6 ">
         {% crispy form %}
    </div>
{% endblock %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.tagit.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.datetimepicker.css' %}">
{% endblock %}


{% block javascript %}


<script src="{% static 'js/jquery.datetimepicker.js' %}"></script>

<script src="{% static 'js/tag-it.min.js' %}"></script>
<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js"></script>

<script type="text/javascript">

$(document).ready(function() {

    setup_autocomplete('event');
    setup_autocomplete('venue');
    setup_autocomplete('bands');

    $('#id_phone_n').mask('(000) 000-0000');
    $('#id_start_time').datetimepicker({
        scrollInput:false,
        closeOnDateSelect:true,
        format:'Y-m-d H:i:00',
        step:30
    });
    $('#id_end_time').datetimepicker({
        scrollInput:false,
        closeOnDateSelect:true,
        format:'Y-m-d H:i:00',
        step:30
    });
    $('#id_event_select').on('blur', function() {
       if ($('#id_event_select').val() === '') {
           $('#id_venue').prop('disabled', false);
           $('#id_bands').prop('disabled', false);

       }
    });

    function setup_autocomplete(type_arg){
        $('#id_'+type_arg+'_select').click(function () {
            $.getJSON('/list/'+type_arg+'/').success(function (data) {
                $('#id_'+type_arg+'_select').autocomplete({
                    minLength: 0,
                    source: data,
                    focus: function( event, ui ) {
                        $( '#id_'+type_arg+'_select' ).val( ui.item.label );
                        return false;
                    },
                    select: function( event, ui ) {
                        if (type_arg==='event') {
                            $('#id_venue').val('');
                            $('#id_bands').val('');
                            $('#id_venue').prop('disabled', true);
                            $('#id_bands').prop('disabled', true);
                        }
                        $( '#id_'+type_arg+'_select' ).val( ui.item.label );
                        $( '#id_'+type_arg).val( ui.item.id );
                        return false;
                    }
                }).autocomplete( 'instance' )._renderItem = function( ul, item ) {
                    return $( '<li>' ).append( '<a><strong>' + item.label + '</strong><br>' + item.desc.substring(0,60) + '</a>' )
                    .appendTo( ul );
                };
            });
        });
    };
});



</script>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load event_tags %}
{% block title %}Home{% endblock %}
{% block content %}

    <section class="mainCotainer" id="home">
        <article></article>
        <div class="legendFeat container-fluid">
            <div class="legend">TICKETSLOTH IS A NEW WAY TO BUY AND SELL TICKETS</div>
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-3">
                    <div class="feat"><img src="static/images/review-icon.svg">
                        <div class="info">
                            <div class="title">REVIEW SYSTEM</div>
                            <div class="des">It was a humorously perilous business for both of us.</div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3">
                    <div class="feat"><img src="static/images/nofees-icon.svg">
                        <div class="info">
                            <div class="title">NO FEES</div>
                            <div class="des">It was a humorously perilous business for both of us.</div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3">
                    <div class="feat"><img src="static/images/setprice-icon.svg">
                        <div class="info">
                            <div class="title">SET YOUR PRICE</div>
                            <div class="des">It was a humorously perilous business for both of us.</div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-3">
                    <div class="feat"><img src="static/images/musicevents-icon.svg">
                        <div class="info">
                            <div class="title">ALL TYPES OF EVENTS</div>
                            <div class="des">It was a humorously perilous business for both of us.</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="upcomingCardsCont">
            {% for event in events_list %}
                {% include "events/event_upcoming_item.html" %}
            {% endfor %}
        </div>
        <div class="recentCont">
            <h2>MOST RECENT LISTINGS IN <span class="accent">{{ request.region.name }}</span></h2>
            <div class="row">
                <div class="col-xs-12 col-md-12">
                    <div class="list">
                        {% for listing in listing_list %}
                            {% include "listings/listing_list_item.html" %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="otherLike">
            <h2>YOU MAY ALSO LIKE</h2>
            {% you_may_also_like request.region 9 %}
        </div>
    </section>
{% endblock %}

templates/listing_list.html
{% extends "base.html" %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block title %}Listings{% endblock %}

{% block content %}
  <h3>Grab these {{ request.region.name }} tickets - or <a href = "{% url 'post' %}">add your own</a></h3>
  <div class="row ">
    <div class="col-md-3">
      <h3 class="filter-head">Filters</h3>
      <form id="ticket-filter-form" method="post" action="{% url 'ticket_search' %}">
        {% crispy form %}
      </form>
    </div>
    <div class="col-md-9">
      {% for listing in ticket_list %}
        {% include 'partial/listing_listitem.html' %}
      {% endfor %}

    </div>
  </div>

  {% include 'partial/pagination.html' %}

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}



<form method="post" action="{% url 'django.contrib.auth.views.login' %}?next={{next}}">
{% csrf_token %}
<table class="login-fields">
    <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
    </tr>
    <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
    </tr>
</table>
<a href="{% url "password_reset_recover" %}">Forgot Password?</a>
<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>


{% endblock %}

templates/post.html
2{% extends "base.html" %}

{% block content %}

<ul class = "nav nav-tabs">
    <li class="active"><a href="#tab_a" data-toggle="tab">Post Listing</a></li>
    <li><a href="#tab_b" data-toggle="tab">Post Event</a></li>
</ul>


<!--                                   tab A -->
<div class = "tab-content">
    <div class = "tab-pane active" id="tab_a">
    <br>

<form>

<div class = "col-xs-12 col-md-6">
  <div class="form-group">
    <label for="ListingTitle">Listing Title</label>
    <input type="text" class="form-control" id="ListingTitle" placeholder="Listing Title">
  </div>

  <div class="form-group">
    <label for="Listing Description">Listing Description</label>
    <input type="text" rows="3" class="form-control" id="ListingDescription" placeholder="Description">
  </div>

  <div class="form-group">
    <label for="Listing Description">Show Date</label>
    <input type="text" rows="3" class="form-control" id="ListingDate" placeholder="Date">
  </div>

 </div>

<div class = "col-xs-12 col-md-6">


<div class="form-group">
    <label for="Venue">Venue</label>
    <input type="text" class="form-control" id="ListingVenue" placeholder="Venue">
</div>


    <div class="form-group">
        <label for="Price">Price</label>
        <input type="text" class="form-control" id="ListingPrice" placeholder="Price">
    </div>

    
    <div class="form-group">
        <label for="Quantity">Quantity</label>
        <input type="text" class="form-control" id="ListingQuant" placeholder="Put 0 if wanted">
    </div>


    <div class="form-group">
        <label for="Artist">Artist</label>
        <input type="text" class="form-control" id="EventArtist" placeholder="Artist">
    </div>
 
<button type="submit" class="btn btn-default pull-right">Submit</button>

</form>

</div>      



</div>


<!--             tab b -->

<div class = "tab-pane" id="tab_b">
        <br>

<form>

<div class = "col-xs-12 col-md-6">
  <div class="form-group">
    <label for="EventName">Event Name</label>
    <input type="text" class="form-control" id="EventName" placeholder="Event Name">
  </div>

  <div class="form-group">
    <label for="Event Description">Event Description</label>
    <input type="text" rows="3" class="form-control" id="EventDescription" placeholder="Event Description">
  </div>

  <div class="form-group">
    <label for="Listing Description">Show Date</label>
    <input type="text" rows="3" class="form-control" id="ListingDate" placeholder="Date">
  </div>

 </div>

<div class = "col-xs-12 col-md-6">



<div class="form-group">
    <label for="Venue">Venue</label>
    <input type="text" class="form-control" id="EventVenue" placeholder="Venue">
</div>



<div class="form-group">
    <label for="Price">Price</label>
    <input type="text" class="form-control" id="EventPrice" placeholder="Price">
</div>



<div class="form-group">
    <label for="Artist">Artist</label>
    <input type="text" class="form-control" id="EventArtist" placeholder="Artist">
</div>


</div>

 <div class="form-group col-xs-12">
    <label for="exampleInputFile">Event Images</label>
    <input type="file" id="exampleInputFile">
 </div>

<button type="submit" class="btn btn-default pull-right" >Submit</button>

</form>
</div> 

{% endblock %}